
annotations:
  images: |
    - name: kube-state-metrics
      image: ghcr.io/nix-containers/kube-state-metrics-nixchart:2.16.0-debian-12-r5
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 2.16.0
description: kube-state-metrics is a simple service that listens to the Kubernetes
  API server and generates metrics about the state of the objects.
home: https://nix-containers.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kube-state-metrics/img/kube-state-metrics-stack-220x234.png
keywords:
- prometheus
- kube-state-metrics
- monitoring
maintainers:
name: kube-state-metrics
sources:
- https://github.com/nix-containers/images
version: 5.1.1
