
annotations:
  images: |
    - name: kibana
      image: ghcr.io/nix-containers/kibana-nixchart:9.1.2-debian-12-r0
    - name: os-shell
      image: ghcr.io/nix-containers/os-shell-nixchart:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 9.1.2
description: Kibana is an open source, browser based analytics and search dashboard
  for Elasticsearch. Kibana strives to be easy to get started with, while also being
  flexible and powerful.
home: https://nix-containers.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kibana/img/kibana-stack-220x234.png
keywords:
- kibana
- analytics
- monitoring
- metrics
- logs
maintainers:
name: kibana
sources:
- https://github.com/nix-containers/images
version: 12.1.11
