
annotations:
  images: |
    - name: os-shell
      image: ghcr.io/nix-containers/os-shell-nixchart:12-debian-12-r51
    - name: pgpool
      image: ghcr.io/nix-containers/pgpool2-nixchart:4.6.3-debian-12-r0
    - name: postgres-exporter
      image: ghcr.io/nix-containers/prometheus-postgres-exporter-nixchart:0.17.1-debian-12-r16
    - name: postgresql-repmgr
      image: ghcr.io/nix-containers/postgres-repmgr-nixchart:17.6.0-debian-12-r2
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 17.6.0
description: This PostgreSQL cluster solution includes the PostgreSQL replication
  manager, an open-source tool for managing replication and failover on PostgreSQL
  clusters.
home: https://nix-containers.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
- postgresql
- repmgr
- pgpool
- postgres
- database
- sql
- replication
- cluster
- high availability
maintainers:
name: postgresql-ha
sources:
- https://github.com/nix-containers/images
version: 16.3.4
