{ mkImage, pkgs, lib, ... }:

# policy-bot - GitHub App for enforcing approval policies on pull requests
# https://github.com/palantir/policy-bot
#
# Split build:
#   - policyBotBin: buildGoModule at v${version}, gives us a Go stdlib that
#     forward-fixes with each nixpkgs bump.
#   - policyBotAssets: pulls the same-version release tarball just to lift
#     out `static/` + `templates/`, which are generated by upstream's Node
#     toolchain (webpack + tailwind + postcss) and would otherwise require
#     an entire JS build to reproduce.
# Then we compose them into a single `share/policy-bot` layout that matches
# what the previous prebuilt image shipped.

let
  version = "1.41.1";

  policyBotBin = pkgs.buildGoModule {
    pname = "policy-bot";
    inherit version;

    src = pkgs.fetchFromGitHub {
      owner = "palantir";
      repo = "policy-bot";
      rev = "v${version}";
      hash = "sha256-BeN8BNhgOMqpPMSh5DfezAL3DwdZD/r/bMEtZGV4ptE=";
    };

    vendorHash = null;

    subPackages = [ "." ];
    ldflags = [ "-s" "-w" "-X main.version=${version}" ];
    env.CGO_ENABLED = 0;
    doCheck = false;
  };

  # The release tarball is the only pre-built source of the webpack'd
  # static/ + templates/ dirs; we lift them out without keeping the
  # Go binary (which we rebuild from source above).
  policyBotAssets = pkgs.stdenv.mkDerivation {
    pname = "policy-bot-assets";
    inherit version;
    src = pkgs.fetchurl {
      url = "https://github.com/palantir/policy-bot/releases/download/v${version}/policy-bot-${version}.tgz";
      hash = "sha256-uweT2favD75ZKNHDXgPpA8Rp5mnONSLPUqv6AwBCllM=";
    };
    dontUnpack = false;
    installPhase = ''
      runHook preInstall
      # sourceRoot is already policy-bot-<version>/, so lift assets directly.
      mkdir -p $out/share/policy-bot
      cp -r static templates $out/share/policy-bot/
      runHook postInstall
    '';
  };

  drv = pkgs.buildEnv {
    name = "policy-bot-${version}";
    paths = [ policyBotBin policyBotAssets ];
  };
in mkImage {
  inherit drv;
  name = "policy-bot";
  tag = "v${version}";
  entrypoint = [ "${drv}/bin/policy-bot" ];
  cmd = [ "--help" ];
  labels = {
    "org.opencontainers.image.title" = "policy-bot";
    "org.opencontainers.image.description" = "GitHub App for enforcing approval policies on pull requests";
    "org.opencontainers.image.version" = version;
    "io.nix-containers.source" = "upstream-source";
  };
}
