
annotations:
  images: |
    - name: mysql
      image: ghcr.io/nix-containers/mysql-nixchart:9.4.0-debian-12-r1
    - name: mysqld-exporter
      image: ghcr.io/nix-containers/prometheus-mysqld-exporter-nixchart:0.17.2-debian-12-r16
    - name: os-shell
      image: ghcr.io/nix-containers/os-shell-nixchart:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 9.4.0
description: MySQL is a fast, reliable, scalable, and easy to use open source relational
  database system. Designed to handle mission-critical, heavy-load production applications.
home: https://nix-containers.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mysql/img/mysql-stack-220x234.png
keywords:
- mysql
- database
- sql
- cluster
- high availability
maintainers:
name: mysql
sources:
- https://github.com/nix-containers/images
version: 14.0.5
