#\!/bin/bash
# BigBang 3.13.0 image build commands - generated from bigbang.txt

nix run .#alertmanager.copyToDockerDaemon
nix run .#alloy.copyToDockerDaemon
nix run .#alloy-operator.copyToDockerDaemon
nix run .#anchore-enterprise.copyToDockerDaemon
nix run .#anchore-enterpriseui.copyToDockerDaemon
nix run .#argocd.copyToDockerDaemon
nix run .#authservice.copyToDockerDaemon
nix run .#backstage.copyToDockerDaemon
nix run .#bats.copyToDockerDaemon
nix run .#bigbang-base.copyToDockerDaemon
nix run .#busybox.copyToDockerDaemon
nix run .#dex.copyToDockerDaemon
nix run .#eck-operator.copyToDockerDaemon
nix run .#elasticsearch.copyToDockerDaemon
nix run .#elasticsearch-exporter.copyToDockerDaemon
nix run .#enterprise-logs-provisioner.copyToDockerDaemon
nix run .#enterprise-metrics.copyToDockerDaemon
nix run .#external-secrets.copyToDockerDaemon
nix run .#fluent-bit.copyToDockerDaemon
nix run .#gatekeeper.copyToDockerDaemon
nix run .#gitaly.copyToDockerDaemon
nix run .#gitlab-base.copyToDockerDaemon
nix run .#gitlab-container-registry.copyToDockerDaemon
nix run .#gitlab-exporter.copyToDockerDaemon
nix run .#gitlab-mailroom.copyToDockerDaemon
nix run .#gitlab-pages.copyToDockerDaemon
nix run .#gitlab-runner.copyToDockerDaemon
nix run .#gitlab-runner-helper.copyToDockerDaemon
nix run .#gitlab-shell.copyToDockerDaemon
nix run .#gitlab-sidekiq.copyToDockerDaemon
nix run .#gitlab-toolbox.copyToDockerDaemon
nix run .#gitlab-webservice.copyToDockerDaemon
nix run .#gitlab-workhorse.copyToDockerDaemon
nix run .#grafana.copyToDockerDaemon
nix run .#grafana-enterprise-logs.copyToDockerDaemon
nix run .#grafana-image-renderer.copyToDockerDaemon
nix run .#harbor-core.copyToDockerDaemon
nix run .#harbor-exporter.copyToDockerDaemon
nix run .#harbor-jobservice.copyToDockerDaemon
nix run .#harbor-portal.copyToDockerDaemon
nix run .#harbor-registry.copyToDockerDaemon
nix run .#harbor-registryctl.copyToDockerDaemon
nix run .#harbor-trivy-adapter.copyToDockerDaemon
nix run .#headlamp.copyToDockerDaemon
nix run .#helm-controller.copyToDockerDaemon
nix run .#istio-install-cni.copyToDockerDaemon
nix run .#istio-pilot.copyToDockerDaemon
nix run .#istio-proxy.copyToDockerDaemon
nix run .#k8s-sidecar.copyToDockerDaemon
nix run .#keycloak.copyToDockerDaemon
nix run .#kiali.copyToDockerDaemon
nix run .#kiali-operator.copyToDockerDaemon
nix run .#kibana.copyToDockerDaemon
nix run .#kube-state-metrics.copyToDockerDaemon
nix run .#kube-webhook-certgen.copyToDockerDaemon
nix run .#kubectl.copyToDockerDaemon
nix run .#kustomize-controller.copyToDockerDaemon
nix run .#kyverno.copyToDockerDaemon
nix run .#kyverno-background-controller.copyToDockerDaemon
nix run .#kyverno-cleanup-controller.copyToDockerDaemon
nix run .#kyverno-cli.copyToDockerDaemon
nix run .#kyverno-plugin.copyToDockerDaemon
nix run .#kyverno-reports-controller.copyToDockerDaemon
nix run .#kyvernopre.copyToDockerDaemon
nix run .#loki.copyToDockerDaemon
nix run .#loki-canary.copyToDockerDaemon
nix run .#loki-helm-test.copyToDockerDaemon
nix run .#mattermost.copyToDockerDaemon
nix run .#mattermost-operator.copyToDockerDaemon
nix run .#mc.copyToDockerDaemon
nix run .#memcached.copyToDockerDaemon
nix run .#memcached-exporter.copyToDockerDaemon
nix run .#metrics-server.copyToDockerDaemon
nix run .#mimir.copyToDockerDaemon
nix run .#minio.copyToDockerDaemon
nix run .#mysql.copyToDockerDaemon
nix run .#neuvector-controller.copyToDockerDaemon
nix run .#neuvector-enforcer.copyToDockerDaemon
nix run .#neuvector-manager.copyToDockerDaemon
nix run .#neuvector-prometheus-exporter.copyToDockerDaemon
nix run .#neuvector-scanner.copyToDockerDaemon
nix run .#nexus.copyToDockerDaemon
nix run .#nginx.copyToDockerDaemon
nix run .#notification-controller.copyToDockerDaemon
nix run .#policy-reporter.copyToDockerDaemon
nix run .#policy-reporter-ui.copyToDockerDaemon
nix run .#postgres.copyToDockerDaemon
nix run .#postgresql.copyToDockerDaemon
nix run .#prometheus.copyToDockerDaemon
nix run .#prometheus-blackbox-exporter.copyToDockerDaemon
nix run .#prometheus-config-reloader.copyToDockerDaemon
nix run .#prometheus-node-exporter.copyToDockerDaemon
nix run .#prometheus-operator.copyToDockerDaemon
nix run .#prometheus-snmp-exporter.copyToDockerDaemon
nix run .#redis.copyToDockerDaemon
nix run .#redis-exporter.copyToDockerDaemon
nix run .#rollout-operator.copyToDockerDaemon
nix run .#sonarqube.copyToDockerDaemon
nix run .#source-controller.copyToDockerDaemon
nix run .#tempo.copyToDockerDaemon
nix run .#tempo-query.copyToDockerDaemon
nix run .#thanos.copyToDockerDaemon
nix run .#twistlock-console.copyToDockerDaemon
nix run .#twistlock-defender.copyToDockerDaemon
nix run .#vault.copyToDockerDaemon
nix run .#vault-csi-provider.copyToDockerDaemon
nix run .#vault-k8s.copyToDockerDaemon
nix run .#velero.copyToDockerDaemon
nix run .#velero-plugin-for-aws.copyToDockerDaemon
nix run .#velero-plugin-for-microsoft-azure.copyToDockerDaemon
nix run .#yq.copyToDockerDaemon
