nix run .#alertmanager.copyToDockerDaemon
nix run .#alloy.copyToDockerDaemon
nix run .#anchore-enterprise.copyToDockerDaemon
nix run .#anchore-enterpriseui.copyToDockerDaemon
nix run .#bats.copyToDockerDaemon
nix run .#bigbang-base.copyToDockerDaemon
nix run .#busybox.copyToDockerDaemon
nix run .#cfssl-self-sign.copyToDockerDaemon
nix run .#dex.copyToDockerDaemon
nix run .#elasticsearch-exporter.copyToDockerDaemon
nix run .#enterprise-logs-provisioner.copyToDockerDaemon
nix run .#enterprise-metrics.copyToDockerDaemon
nix run .#external-secrets.copyToDockerDaemon
nix run .#fluent-bit.copyToDockerDaemon
nix run .#gitlab-base.copyToDockerDaemon
nix run .#gitlab-container-registry.copyToDockerDaemon
nix run .#gitlab-pages.copyToDockerDaemon
nix run .#gitlab-runner.copyToDockerDaemon
nix run .#gitlab-runner-helper.copyToDockerDaemon
nix run .#gitlab-shell.copyToDockerDaemon
nix run .#gitlab-workhorse.copyToDockerDaemon
nix run .#grafana-enterprise-logs.copyToDockerDaemon
nix run .#keycloak.copyToDockerDaemon
nix run .#kube-state-metrics.copyToDockerDaemon
nix run .#kubectl.copyToDockerDaemon
nix run .#kyverno.copyToDockerDaemon
nix run .#kyvernopre.copyToDockerDaemon
nix run .#loki.copyToDockerDaemon
nix run .#loki-helm-test.copyToDockerDaemon
nix run .#mattermost.copyToDockerDaemon
nix run .#mc.copyToDockerDaemon
nix run .#memcached.copyToDockerDaemon
nix run .#metrics-server.copyToDockerDaemon
nix run .#mimir.copyToDockerDaemon
nix run .#minio.copyToDockerDaemon
nix run .#mysql.copyToDockerDaemon
nix run .#nginx.copyToDockerDaemon
nix run .#postgres.copyToDockerDaemon
nix run .#postgresql.copyToDockerDaemon
nix run .#prometheus.copyToDockerDaemon
nix run .#prometheus-blackbox-exporter.copyToDockerDaemon
nix run .#prometheus-node-exporter.copyToDockerDaemon
nix run .#prometheus-redis-exporter.copyToDockerDaemon
nix run .#prometheus-snmp-exporter.copyToDockerDaemon
nix run .#redis.copyToDockerDaemon
nix run .#tempo.copyToDockerDaemon
nix run .#tempo-query.copyToDockerDaemon
nix run .#thanos.copyToDockerDaemon
nix run .#trivy.copyToDockerDaemon
nix run .#twistlock-console.copyToDockerDaemon
nix run .#twistlock-defender.copyToDockerDaemon
nix run .#vault.copyToDockerDaemon
nix run .#velero.copyToDockerDaemon
nix run .#yq.copyToDockerDaemon
