
annotations:
  images: |
    - name: kubectl
      image: ghcr.io/nix-containers/kubectl-nixchart:1.33.4-debian-12-r0
    - name: os-shell
      image: ghcr.io/nix-containers/os-shell-nixchart:12-debian-12-r51
    - name: redis
      image: ghcr.io/nix-containers/redis-nixchart:8.2.1-debian-12-r0
    - name: redis-exporter
      image: ghcr.io/nix-containers/prometheus-redis-exporter-nixchart:1.76.0-debian-12-r0
    - name: redis-sentinel
      image: ghcr.io/nix-containers/redis-sentinel-nixchart:8.2.1-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.2.1
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://nix-containers.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
name: redis
sources:
- https://github.com/nix-containers/images
version: 23.1.1
