
annotations:
  images: |
    - name: etcd
      image: ghcr.io/nix-containers/etcd-nixchart:3.6.4-debian-12-r3
    - name: os-shell
      image: ghcr.io/nix-containers/os-shell-nixchart:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 3.6.4
description: etcd is a distributed key-value store designed to securely store data
  across a cluster. etcd is widely used in production on account of its reliability,
  fault-tolerance and ease of use.
home: https://nix-containers.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/etcd/img/etcd-stack-220x234.png
keywords:
- etcd
- cluster
- database
- cache
- key-value
maintainers:
name: etcd
sources:
- https://github.com/nix-containers/images
version: 12.0.20
